#!/bin/bash 

graph=/home/elmazo/graph.txt 
for i in {1..60};
do
server_info=$(curl -H 'Content-Type: application/json' -d '{"method":"server_info","params":[{}]}' https://s1.ripple.com:51234) 
time=$(echo $server_info | jq -r ".result.info.time")
seq=$(echo $server_info | jq -r ".result.info.validated_ledger.seq")
time2=$(echo $time | cut -d "." -f1) 
#echo $time2
#echo $seq
echo "$time2" , "$seq" >> "$graph";
sleep 10;
done

gnuplot -persist <<-EOFMarker
	set datafile separator ","
	set xdata time
	set timefmt "%Y-%b-%d %H:%M:%S"
	set format x "%Y-%b-%d %H:%M:%S"
	set xrange [time(0) - 1*60*60:time(0) + 1*60*60]
	set format y "%f"
	plot "$graph" using 1:2 with linespoints
EOFMarker


